-- SELECT THE DATABSE
USE MIT01;


-- A.SALES PERFORMANCE ANALYSIS

-- 1.TOTAL SALES
SELECT 
    FORMAT(SUM(SALES), 'N2')  AS TOTAL_SALES
FROM ORDERS;

-- 2.TOTAL PROFIT
SELECT 
    FORMAT(SUM(PROFIT), 'N2')  AS TOTAL_PROFIT
FROM ORDERS;

-- 3.PROFIT MARGIN(%)
SELECT 
    ROUND(SUM(PROFIT)/SUM(SALES) * 100,2) AS PROFIT_MARGIN 
FROM ORDERS;

-- 4.RETURN RATE
SELECT
    100.0 * COUNT(R.ORDER_ID) / COUNT(O.ORDER_ID) AS RETURN_RATE
FROM ORDERS O
LEFT JOIN RETURNS R
    ON O.ORDER_ID = R.ORDER_ID;

-- 5.AVERAGE DISCOUNT
SELECT AVG(DISCOUNT) *100.0 AS AVERAGE_DISCOUNT 
FROM ORDERS;

-- 6.YEARLY SALES & PROFIT TREND
SELECT 
    YEAR(ORDER_DATE) AS YEAR,
    FORMAT(ROUND(SUM(SALES), 2),'N2') AS TOTAL_SALES,
    FORMAT(ROUND(SUM(PROFIT), 2),'N2') AS TOTAL_PROFIT
FROM ORDERS
GROUP BY YEAR(ORDER_DATE)
ORDER BY YEAR;

-- 7.MONTHLY SALES & PROFIT TREND
SELECT 
    MONTH(ORDER_DATE) AS MONTH,
    FORMAT(ROUND(SUM(SALES), 2),'N2') AS TOTAL_SALES,
    FORMAT(ROUND(SUM(PROFIT), 2),'N2') AS TOTAL_PROFIT
FROM ORDERS
GROUP BY MONTH(ORDER_DATE)
ORDER BY MONTH;

-- 8.SALES BY CATEGORY & SUB-CATEGORY
SELECT 
    CATEGORY,
    SUBCATEGORY,
    ROUND(SUM(SALES), 2) AS TOTAL_SALES
FROM ORDERS
GROUP BY CATEGORY, SUBCATEGORY
ORDER BY TOTAL_SALES DESC;

-- 9.TOP 10 PRODUCTS BY SALES
SELECT TOP 10
    PRODUCT_NAME,
    ROUND(SUM(SALES), 2) AS TOTAL_SALES
FROM ORDERS
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_SALES DESC;

-- 10.HIGH SALES BUT NEGATIVE PROFIT PRODUCTS
SELECT 
    PRODUCT_NAME,
    ROUND(SUM(SALES), 2) AS TOTAL_SALES,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT
FROM ORDERS
GROUP BY PRODUCT_NAME
HAVING SUM(SALES) > 5000
   AND SUM(PROFIT) < 0
ORDER BY TOTAL_SALES DESC;


-- B.REGIONAL & LOCATION ANALYSIS

-- 1.SALES & PROFIT BY REGION
SELECT 
    REGION,
    ROUND(SUM(SALES), 2) AS TOTAL_SALES,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT
FROM ORDERS
GROUP BY REGION
ORDER BY TOTAL_PROFIT DESC;

-- 2.TOP 5 STATES BY PROFIT
SELECT TOP 5
    STATE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT
FROM ORDERS
GROUP BY STATE
ORDER BY TOTAL_PROFIT DESC;

-- 3.BOTTOM 5 STATES (LOSS MAKING)
SELECT TOP 5
    STATE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT
FROM ORDERS
GROUP BY STATE
ORDER BY TOTAL_PROFIT ASC;

-- 4.REGIONS WITH HIGH DISCOUNTS BUT LOW PROFIT
SELECT 
    REGION,
    ROUND(AVG(DISCOUNT), 2) AS AVG_DISCOUNT,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT
FROM ORDERS
GROUP BY REGION
ORDER BY AVG_DISCOUNT DESC;


-- C.CUSTOMER ANALYSIS

-- 1.AVERAGE ORDER VALUE (AOV)
SELECT 
    ROUND(SUM(SALES) / COUNT(DISTINCT ORDER_ID), 2) AS AVG_ORDER_VALUE
FROM ORDERS;

-- 2.SALES & PROFIT BY SEGMENT
SELECT 
    SEGMENT,
    ROUND(SUM(SALES), 2) AS TOTAL_SALES,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT
FROM ORDERS
GROUP BY SEGMENT
ORDER BY TOTAL_PROFIT DESC;

-- 3.TOP 10 CUSTOMERS BY PROFIT
SELECT TOP 10
    CUSTOMER_NAME,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT
FROM ORDERS
GROUP BY CUSTOMER_NAME
ORDER BY TOTAL_PROFIT DESC;

-- 4.CUSTOMERS WITH HIGH SALES BUT LOSS
SELECT 
    CUSTOMER_NAME,
    ROUND(SUM(SALES), 2) AS TOTAL_SALES,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT
FROM ORDERS
GROUP BY CUSTOMER_NAME
HAVING SUM(SALES) > 3000
   AND SUM(PROFIT) < 0;


-- D.PRODUCT & CATEGORY PROFITABILITY

-- 1.LOSS MAKING SUB CATEGORIES
SELECT 
    SUBCATEGORY,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT
FROM ORDERS
GROUP BY SUBCATEGORY
HAVING SUM(PROFIT) < 0
ORDER BY TOTAL_PROFIT;

-- 2.HIGH DISCOUNT – LOW PROFIT PRODUCTS
SELECT 
    PRODUCT_NAME,
    ROUND(AVG(DISCOUNT), 2) AS AVG_DISCOUNT,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT
FROM ORDERS
GROUP BY PRODUCT_NAME
HAVING AVG(DISCOUNT) > 0.3
   AND SUM(PROFIT) < 0;

-- 3.QUANTITY VS PROFIT
SELECT 
    QUANTITY,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT
FROM ORDERS
GROUP BY QUANTITY
ORDER BY QUANTITY;

-- 4.PROFIT MARGIN BY DISCOUNT
SELECT 
    DISCOUNT,
    ROUND((SUM(PROFIT) / SUM(SALES)) * 100, 2) AS PROFIT_MARGIN_PCT
FROM ORDERS
GROUP BY DISCOUNT
ORDER BY DISCOUNT;


-- E.ORDER & SHIPPING DATE ANALYSIS

-- 1.AVERAGE SHIPPING TIME
SELECT
    ROUND(AVG(DATEDIFF(DAY, ORDER_DATE, SHIP_DATE)), 2) AS AVG_SHIPPING_DAYS
FROM ORDERS;

-- 2.ORDERS BY SHIPPING MODE
SELECT 
    SHIP_MODE,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM ORDERS
GROUP BY SHIP_MODE;

-- 3.PROFIT BY SHIPPING MODE
SELECT 
    SHIP_MODE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT
FROM ORDERS
GROUP BY SHIP_MODE
ORDER BY TOTAL_PROFIT DESC;


-- F.WINDOW FUNCTIONS

-- 1.RANK PRODUCTS BY PROFIT WITHIN CATEGORY
SELECT 
    CATEGORY,
    PRODUCT_NAME,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    RANK() OVER (PARTITION BY CATEGORY ORDER BY SUM(PROFIT) DESC) AS RANK_IN_CATEGORY
FROM ORDERS
GROUP BY CATEGORY, PRODUCT_NAME;

-- 2.MONTH-OVER-MONTH SALES GROWTH
WITH MONTHLY_SALES AS (
    SELECT
        YEAR(ORDER_DATE) AS ORDER_YEAR,
        MONTH(ORDER_DATE) AS ORDER_MONTH,
        SUM(SALES) AS TOTAL_SALES
    FROM ORDERS
    GROUP BY
        YEAR(ORDER_DATE),
        MONTH(ORDER_DATE)
)
SELECT
    ORDER_YEAR,
    ORDER_MONTH,
    TOTAL_SALES,
    TOTAL_SALES
        - LAG(TOTAL_SALES) OVER (
            ORDER BY ORDER_YEAR, ORDER_MONTH
          ) AS MOM_GROWTH
FROM MONTHLY_SALES
ORDER BY
    ORDER_YEAR,
    ORDER_MONTH;
